export const dailyForecastConstants = {
  GETALL_REQUEST: 'FORECASTS_GETALL_REQUEST',
  GETALL_SUCCESS: 'FORECASTS_GETALL_SUCCESS',
  GETALL_FAILURE: 'FORECASTS_GETALL_FAILURE',

  GETBYCOORD_REQUEST: 'FORECASTS_GETBYCOORD_REQUEST',
  GETBYCOORD_SUCCESS: 'FORECASTS_GETBYCOORD_SUCCESS',
  GETBYCOORD_FAILURE: 'FORECASTS_GETBYCOORD_FAILURE',
};
