version: '3.5'

services:
  db:
    image: mysql:8.0
    container_name: weatherDb
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: weatherdb
    volumes:
      - ../data/mysql:/var/lib/mysql

  phpmyadmin:
    depends_on:
    - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
     - '8850:80'
    environment:
      PMA_HOST: db
