export const currentForecastConstants = {
  GETALL_REQUEST: 'FORECASTS_GETALL_REQUEST',
  GETALL_SUCCESS: 'FORECASTS_GETALL_SUCCESS',
  GETALL_FAILURE: 'FORECASTS_GETALL_FAILURE',

  GETBYCITY_REQUEST: 'FORECASTS_GETBYCITY_REQUEST',
  GETBYCITY_SUCCESS: 'FORECASTS_GETBYCITY_SUCCESS',
  GETBYCITY_FAILURE: 'FORECASTS_GETBYCITY_FAILURE',

  FETCHBYCITY_REQUEST: 'FORECASTS_FETCHBYCITY_REQUEST',
  FETCHBYCITY_SUCCESS: 'FORECASTS_FETCHBYCITY_SUCCESS',
  FETCHBYCITY_FAILURE: 'FORECASTS_FETCHBYCITY_FAILURE',

  CHANGECITY_REQUEST: 'FORECASTS_CHANGECITY_REQUEST',
  CHANGECITY_SUCCESS: 'FORECASTS_CHANGECITY_SUCCESS',
  CHANGECITY_FAILURE: 'FORECASTS_CHANGECITY_FAILURE',
};
